apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cuttlefish-group
  description: Team Cuttlefish provides useful, extensible solutions to current and future customers by anticipating and reacting to their needs. Cuttlefish will be obsessed with building functionality in the Dev Platform and Mission Control so that Transposit users can eliminate tedium, build efficient & useful workflows, and find new and interesting ways to automate their repetitive tasks. The team will always attempt to meet the customer at their level of expertise, tailoring the approach and level of effort accordingly
spec:
  type: service-group
  profile:
    displayName: Cuttlefish Group
    email: solutions@transposit.com
    picture: https://cdn.shopify.com/s/files/1/0980/9618/products/north-drinkware-the-mt-hood-tumbler-11186413253.jpg
  children: [Solutions]
  members: [ryan,cory]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: solutions-group
  description: own the integrations for internal and external customers where the developer platform must provide extensible actions and connectors. Team Cuttlefish will act as the escalation point for both customer support and sales engineers where knowledge beyond their scope is required. 
spec:  
  type: service-group
  profile:
    displayName: Solutions Engineering Group
    email: solutions@transposit.com
    picture: https://cdn.shopify.com/s/files/1/0980/9618/products/north-drinkware-the-mt-hood-tumbler-11186413253.jpg
  parent: Cuttlefish
  children: []
  members: [ryan,cory]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ryan
spec:
  profile:
    displayName: Ryan Taylor
    email: ryan@transposit.com
    picture: https://www.svgrepo.com/show/241591/clown-avatar.svg
  memberOf: [Solutions]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cory
spec:
  profile:
    displayName: Cory Finger
    email: cory@transposit.com
    picture: https://www.shareicon.net/data/512x512/2016/04/22/753637_wizard_512x512.png
  memberOf: [Cuttlefish Group]
---
 apiVersion: backstage.io/v1alpha1
 kind: System
 metadata:
   name: cuttlefish-tools-system
   description: Handy tools that enable the Solutions Engineering organization
 spec:
   owner: solutions-group
   domain: solutions
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cuttlefish-apps-component
  description: The scripts, actions, runbooks, and other objects built by Cuttlefish, used by customers 
  labels:
    "critical": "true"
    "release" : "stable"
    "environment" : "production"
    "tier" : "frontend"
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/ryantaylor16/backstage
    github.com/project-slug: ryantaylor16/backstage
  tags:
    - java
    - python
    - javascript
    - ruby
    - elixir
  links:
    - url: https://transposit.atlassian.net/jira/software/c/projects/MCW/boards/59
      title: Jira Board
      icon: jira
    - url: https://transposit.slack.com/archives/C01G8UYMEFP
      title: Team Slack
      icon: slack
spec:
  type: service
  lifecycle: production
  owner: cuttlefish-group
  system: cuttlefish-tools-system
  dependsOn:
    - component:Neutrino
  providesApis:
    - starwars-graphql
---
# apiVersion: backstage.io/v1alpha1
# kind: Domain
# metadata:
#   name: cuttlefish-domain
#  description: The Cuttlefish Domain
# spec:
#   owner: solutions-group
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cuttlefish-resource
  description: Cuttlefish Resource
spec:
  type: cluster
  owner: cuttlefish-group
  system: cuttlefish-tools-system
---
